esphome:
  name: esptest
  friendly_name: ESPTest

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "bsaIO2P/WJjrj91bDcAH5LAmBeQKrcrIRYq2aMXUFdA="

ota:
  platform: "esphome"
  password: "2e7988be0f583a9489438605afeb07ca"

wifi:
  ssid: xxxxxxxxxx
  password: xxxxxxxxxx

  ap:
    ssid: "Esptest Fallback Hotspot"
    password: "TkbT1LSU0yni"

captive_portal:

external_components:
  - source:
      type: local
      path: components

uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 9600

diesel_heater:
  id: my_diesel_heater

sensor:
  - platform: template
    name: "Diesel Heater Run State"
    lambda: |-
      return id(my_diesel_heater).get_run_state();
    update_interval: 1s